version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    environment:
      PORT: 4000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: app
      DB_PASSWORD: app
      DB_NAME: app
      NODE_ENV: production
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=http://backend:4000/api
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
